version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sec
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    ports:
      - "9000:9000"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  ingestion-service:
    build: ./ingestion-service
    depends_on:
      - minio
  parser-service:
    build: ./parser-service
    depends_on:
      - minio
  chunker-service:
    build: ./chunker-service
    depends_on:
      - kafka
      - postgres
  embedding-service:
    build: ./embedding-service
    depends_on:
      - postgres
      - elasticsearch
  retrieval-service:
    build: ./retrieval-service
    depends_on:
      - postgres
      - elasticsearch
  qa-service:
    build: ./qa-service
