server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
sec:
  api: https://data.sec.gov/api/
minio:
  bucket: filings
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
kafka:
  topic: filings-parsed
retrieval:
  base-url: http://retrieval-service:8085
