server:
  port: 8085
spring:
  datasource:
    url: jdbc:h2:mem:retrieval;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
