server:
  port: 8083
spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://postgres:5432/sec
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
